#!/bin/sh

clientID=c79f52fb8ecd14f65a3e
clientSecret=f62012f87a0308d350b12808ad0c651eb02f620d
newBranchName=$1

echo "checking out branch: $newBranchName"
git checkout -b $newBranchName

echo "create some test file"
touch testFile

#-----------------------------------
echo "make a change"
echo "I'm a change!" > testFile

echo "commit that change"
git add .
git commit -m "I made a change"

#-----------------------------------
echo "make another change"
echo "I'm another change!" > testFile

echo "commit that change"
git add .
git commit -m "I made 2nd change"

#-----------------------------------
echo "make a third change"
echo "I'm third change!" > testFile

echo "commit that change"
git add .
git commit -m "I made 3rd change"

#-----------------------------------
echo "push those changes!"
git push

#-----------------------------------
echo "create a pull request"
hub pull-request
