#!/bin/sh

totalIterations=$1
currentIteration=0

echo "Total iterations: $totalIterations"

while [ "$currentIteration" -lt $totalIterations ]; do
  newBranchName="test_branch_$currentIteration"

  echo "checking out branch: $newBranchName"
  git checkout -b $newBranchName

  echo "create some test file"
  touch "testFile_$currentIteration"

  #-----------------------------------
  echo "make a change"
  echo "I'm a change!" > testFile

  echo "commit that change"
  git add .
  git commit -m "I made a change"

  #-----------------------------------
  echo "make another change"
  echo "I'm another change!" > testFile

  echo "commit that change"
  git add .
  git commit -m "I made 2nd change"

  #-----------------------------------
  echo "make a third change"
  echo "I'm third change!" > testFile

  echo "commit that change"
  git add .
  git commit -m "I made 3rd change"

  #-----------------------------------
  echo "push those changes!"
  git push

  #-----------------------------------
  echo "create a pull request"
  hub pull-request

  currentIteration=$((currentIteration+1))
done
